#!/usr/bin/env python3
"""Shared deterministic Codex-agent generation and installation helpers."""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import tempfile
import tomllib
from pathlib import Path
from typing import Any

MANIFEST_FILE = "manifest.json"
OWNERSHIP_FILE = ".product-skills-agents.json"
SCHEMA_VERSION = "1"
MANAGER = "product-skills"

AGENTS = (
    {
        "source_name": "legal",
        "source_path": "agents/legal.md",
        "generated_file": "product-skills-legal.toml",
        "agent_name": "product_skills_legal",
        "display_name": "Anthony",
    },
    {
        "source_name": "marketer",
        "source_path": "agents/marketer.md",
        "generated_file": "product-skills-marketer.toml",
        "agent_name": "product_skills_marketer",
        "display_name": "Caal",
    },
)
AGENT_FILES = tuple(agent["generated_file"] for agent in AGENTS)


def codex_prelude(display_name: str) -> str:
    return f"""# Codex compatibility prelude (Product Skills)

You are running as the Codex custom-agent adapter for {display_name}. Preserve
the role, constraints, and output style in the canonical Product Skills prompt
below.

## Runtime translation (Claude Code to Codex)

- For `Skill` or `<plugin>:<name>` references, locate the matching `SKILL.md`
  exposed to this Codex session, read it completely, and follow it. Never invent
  a skill or bypass its bundled scripts.
- Use Codex filesystem, shell, planning, browser, and collaboration tools in
  place of Claude-specific `Read`, `Write`, `Bash`, and `TodoWrite` tools.
- `${{CLAUDE_PLUGIN_ROOT}}` means the relevant installed plugin root. Resolve
  scripts and assets from the selected skill directory or its plugin root.
- Claude model routing and tool allowlists are informational only; inherit the
  Codex session model and use only tools actually available in this session.
- Do not edit global Codex configuration or assume Claude-only plugin commands.

---
"""


def sha256(data: bytes) -> str:
    return "sha256:" + hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256(path.read_bytes())


def plugin_root(start: Path | None = None) -> Path:
    env = os.environ.get("PRODUCT_SKILLS_PLUGIN_ROOT") or os.environ.get("CLAUDE_PLUGIN_ROOT")
    if env:
        root = Path(env).expanduser().resolve()
        if all((root / agent["source_path"]).is_file() for agent in AGENTS):
            return root
        raise SystemExit(f"Product Skills plugin root is invalid: {root}")
    here = (start or Path(__file__)).resolve()
    for parent in [here, *here.parents]:
        if all((parent / agent["source_path"]).is_file() for agent in AGENTS):
            return parent
    raise SystemExit("Could not locate the Product Skills plugin root")


def parse_source(path: Path) -> dict[str, str]:
    raw = path.read_text(encoding="utf-8")
    match = re.match(r"\A---\r?\n(.*?)\r?\n---\r?\n(.*)\Z", raw, re.DOTALL)
    if not match:
        raise ValueError(f"{path}: invalid agent frontmatter")
    frontmatter, body = match.groups()
    fields: dict[str, str] = {}
    lines = frontmatter.splitlines()
    index = 0
    while index < len(lines):
        field = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", lines[index])
        if not field:
            index += 1
            continue
        key, value = field.groups()
        if value.strip() in {">", ">-", "|", "|-"}:
            folded = value.strip().startswith(">")
            index += 1
            block: list[str] = []
            while index < len(lines) and (not lines[index] or lines[index][0].isspace()):
                block.append(lines[index].strip())
                index += 1
            fields[key] = (" " if folded else "\n").join(block).strip()
            continue
        fields[key] = value.strip().strip("\"'")
        index += 1
    if not fields.get("description") or not fields.get("version"):
        raise ValueError(f"{path}: description and version are required")
    return {
        "raw": raw,
        "description": fields["description"],
        "version": fields["version"],
        "body": body,
    }


def toml_multiline(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    return '"""' + escaped + '"""'


def generated_text(agent: dict[str, str], source: dict[str, str]) -> str:
    source_hash = sha256(source["raw"].encode())
    instructions = codex_prelude(agent["display_name"]) + "\n" + source["body"]
    return (
        "# Generated by scripts/codex-agents/generate.py — DO NOT EDIT BY HAND\n"
        f"# source: {agent['source_path']}\n"
        f"# source_version: {source['version']}\n"
        f"# source_hash: {source_hash}\n"
        f"# generator_schema_version: {SCHEMA_VERSION}\n\n"
        f"name = \"{agent['agent_name']}\"\n"
        f"description = {toml_multiline(source['description'])}\n"
        f"developer_instructions = {toml_multiline(instructions)}\n"
    )


def build(root: Path) -> tuple[dict[str, str], dict[str, Any]]:
    generated: dict[str, str] = {}
    entries: list[dict[str, Any]] = []
    for agent in AGENTS:
        source = parse_source(root / agent["source_path"])
        text = generated_text(agent, source)
        generated[agent["generated_file"]] = text
        entries.append(
            {
                "source_name": agent["source_name"],
                "source_path": agent["source_path"],
                "source_version": source["version"],
                "source_hash": sha256(source["raw"].encode()),
                "generated_file": agent["generated_file"],
                "generated_hash": sha256(text.encode()),
                "agent_name": agent["agent_name"],
                "default_install": True,
            }
        )
    manifest = {
        "schema_version": "1",
        "generator_schema_version": SCHEMA_VERSION,
        "manager": MANAGER,
        "agents": entries,
    }
    return generated, manifest


def json_text(value: Any) -> str:
    return json.dumps(value, indent=2, ensure_ascii=False) + "\n"


def atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp_name, path)
    finally:
        Path(temp_name).unlink(missing_ok=True)


def atomic_copy(source: Path, target: Path) -> None:
    atomic_write(target, source.read_text(encoding="utf-8"))


def load_json(path: Path, default: Any) -> Any:
    if not path.is_file():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def validate_adapter(path: Path, expected_name: str) -> None:
    with path.open("rb") as handle:
        parsed = tomllib.load(handle)
    if parsed.get("name") != expected_name:
        raise ValueError(f"{path}: unexpected agent name")


def quarantine(path: Path, target_dir: Path) -> Path:
    trash = target_dir / ".product-skills-agents-trash"
    trash.mkdir(parents=True, exist_ok=True)
    destination = trash / path.name
    counter = 1
    while destination.exists() or destination.is_symlink():
        destination = trash / f"{path.name}.{counter}"
        counter += 1
    shutil.move(path, destination)
    return destination
